import type { Metadata } from 'next';
import '../globals.css';
import Header from '../../components/UI/Header';
import Footer from '../../components/UI/Footer';

export async function generateMetadata({params}: {params: Promise<{ locale: string }> }): Promise<Metadata> {
const { locale } = await params;

return {
title: 'Create Next App',
description: 'Generated by create next app',
alternates: {
canonical: `https://www.yourcompany.com/${locale}`,
languages: {
'en': 'https://www.yourcompany.com/en',
'fr': 'https://www.yourcompany.com/fr',
'de': 'https://www.yourcompany.com/de',
'ja': 'https://www.yourcompany.com/ja',
'ko': 'https://www.yourcompany.com/ko',
'x-default': 'https://www.yourcompany.com/en',
},
},
};
}

export default async function RootLayout({
children,
params,
}: {
children: React.ReactNode;
params: Promise<{ locale: string }>;
}) {
const { locale } = await params;

return (
<>
<Header />
<main className="flex-grow">{children}</main>
<Footer />
</>
);
}